### Reference
https://github.com/minhnq97/pytorch-transformer-text-classification

In [92]:
import os
import numpy as np

In [93]:
DATA_PATH = "data"
VOCAL_FILE = "vocab.txt"
EMBEDDING_FILE = "embeddings.npy"
vocal_file_path = os.path.join(DATA_PATH, VOCAL_FILE)
embedding_file_path = os.path.join(DATA_PATH, EMBEDDING_FILE)

In [94]:
data_list = [os.path.join(DATA_PATH, filename) 
             for filename in sorted(os.listdir(DATA_PATH))
            if filename[0].isdigit()]

In [102]:
np.load(data_list[0])[:50].astype(int)


array([  50,  325,  152,  198,    0,  199,  557, 1797, 2122,   19,  267,
       1189, 1196,  789,  466, 1320,  207,   28, 2122,    3,  437,  335,
        263,   50,  325,  152,  198,    0,   37,  267,   15,  902,  113,
        789,  466,   64,  488,    4,   66,  158,  267,  105,  528, 1797,
       2122,    1,  152,  198,    5,  410])

In [103]:
f = open(vocal_file_path, "r")
vocab = [line.strip().split() for line in f.readlines()]
vocab_list = [[line[0], int(line[1])] for line in vocab]
vocab = {key: value for value, key  in vocab_list}
vocab_array = np.array([word for word, _ in vocab_list])

In [109]:
# sau cứu tự trở của máy phí tiger e cũng nội rau biết.

In [110]:
data_list

['data/0.npy',
 'data/1.npy',
 'data/2.npy',
 'data/3.npy',
 'data/4.npy',
 'data/5.npy',
 'data/6.npy',
 'data/7.npy',
 'data/8.npy',
 'data/9.npy']

In [108]:
" ".join(vocab_array[np.load(data_list[0])[:50].astype(int)])

'sau cứu tự trở của máy phí tiger e cũng nội rau biết. cải tương nghèo ý ra e là tích tiếng lúc sau cứu tự trở của nhưng nội khi cà mình cải tương đồng tinh một cơ tài nội chủ hoàng tiger e và tự trở các viện'

In [91]:
data_list

['data/0.npy',
 'data/1.npy',
 'data/2.npy',
 'data/3.npy',
 'data/4.npy',
 'data/5.npy',
 'data/6.npy',
 'data/7.npy',
 'data/8.npy',
 'data/9.npy']

In [10]:
with open(vocal_file_path, "rt") as f:
    n_vocab = len(f.readlines())

In [12]:
f = open(vocal_file_path, "r")
vocab = [line.strip().split() for line in f.readlines()]
vocab_list = [[line[0], int(line[1])] for line in vocab]
vocab = {key: value for value, key  in vocab_list}
vocab_array = np.array([word for word, _ in vocab_list])

In [20]:
data_list

['data/0.npy',
 'data/1.npy',
 'data/2.npy',
 'data/3.npy',
 'data/4.npy',
 'data/5.npy',
 'data/6.npy',
 'data/7.npy',
 'data/8.npy',
 'data/9.npy']

In [21]:
classes = len(data_list)
class_weights = np.zeros(classes)
result = []
for cls in range(classes):
    result.append(np.load(os.path.join(DATA_PATH,"{}.npy".format(cls))))
    class_weights[cls] = len(result[cls])
total_tokens = np.sum(class_weights)
class_weights = total_tokens / class_weights
class_weights = class_weights / np.mean(class_weights)

In [27]:
vocab_array[0]

'của'

In [23]:
" ".join(vocab_array[result[0][:10].astype(int)])

'sau cứu tự trở của máy phí tiger e cũng'

In [32]:
len(vocab_array)

228701

In [112]:
embedding_arr = np.load(embedding_file_path)
embedding_arr.shape

(7499, 256)

In [30]:
embedding_arr[0]

array([ 0.12443245, -1.06767595, -0.86100352, -0.22868277, -0.18263325,
       -0.83897579, -0.54271376, -0.14510156,  1.45080626, -1.31177831,
       -0.09934112, -0.50401318,  0.18361984, -0.87430686,  0.4183397 ,
       -0.38293737, -0.46698889, -0.3168374 ,  0.2094702 ,  0.0927381 ,
       -0.40501601, -0.03243043, -0.97817194,  0.39318395,  0.44378737,
       -0.09778501,  0.98345089,  0.38792226,  0.3072651 ,  0.69894433,
       -0.61095971, -0.00980708,  0.17413437, -0.8591373 , -0.35638359,
        0.50950557, -0.74880069, -0.86677134, -0.2526764 ,  0.42806679,
        0.85238779, -0.4667412 , -0.82140058,  0.30189058,  0.24839553,
        1.38992858,  0.50543082, -1.48028874, -0.01180037, -0.17234892,
       -0.85603124,  0.20224749,  1.66323972, -0.66056222, -0.39488134,
       -0.24969529,  0.45999593, -0.94671363, -0.10207363, -0.28477326,
       -0.0461395 ,  0.36013049,  0.50129986,  0.64350557,  0.35307923,
        0.62748319,  0.89732498,  0.78383476, -0.67000973, -0.22

In [113]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import math
from torch.autograd import Variable
import copy

In [119]:
emb = nn.Embedding(10, 3)
device = torch.device("cpu")
idx = torch.tensor([3, 5, 1, 2], dtype=torch.int64, device=device)

In [35]:
emb = nn.Embedding(10, 3)
device = torch.device("cpu")

In [129]:
idx = torch.tensor([3, 5, 1, 2], dtype=torch.int64, device=device)
emb(idx)

tensor([[ 1.0729, -0.9660, -2.2049],
        [ 0.0266, -1.8962, -0.2807],
        [-1.2198,  0.2665,  0.5991],
        [-1.4453, -0.3937, -0.5637]], grad_fn=<EmbeddingBackward>)

array([  50,  325,  152,  198,    0,  199,  557, 1797, 2122,   19,  267,
       1189, 1196,  789,  466, 1320,  207,   28, 2122,    3,  437,  335,
        263,   50,  325,  152,  198,    0,   37,  267,   15,  902,  113,
        789,  466,   64,  488,    4,   66,  158,  267,  105,  528, 1797,
       2122,    1,  152,  198,    5,  410])

In [39]:
emb.weight

Parameter containing:
tensor([[ 0.9026,  0.2722,  1.0176],
        [-0.2384, -1.7833,  1.1430],
        [ 0.2300, -1.0885,  0.8840],
        [ 0.4738, -0.0573, -0.2484],
        [-0.1403,  0.1988, -0.0471],
        [-0.0246,  0.5285,  1.1919],
        [ 0.3878,  0.3332, -1.8052],
        [ 0.8330,  0.2166, -0.1915],
        [-0.5946,  1.1952,  2.6624],
        [ 1.7488, -0.4235,  2.9538]], requires_grad=True)

In [46]:
class Embeddings(nn.Module):
    def __init__(self, d_model, vocab):
        super(Embeddings, self).__init__()
        self.lut = nn.Embedding(vocab, d_model)
        self.d_model = d_model

    def forward(self, x):
        return self.lut(x) * math.sqrt(self.d_model)


In [122]:

len(vocab_list)

228701

In [123]:
my_embedding = Embeddings(len(vocab_list), 512)

In [126]:
vocab_list[3]

['là', 3]

In [127]:
vocab_list[5]

['các', 5]

In [131]:
idx = torch.tensor([3, 5, 1, 2], dtype=torch.int64, device=device)

my_embedding

Embeddings(
  (lut): Embedding(512, 228701)
)

In [135]:
idx

tensor([  50,  325,  152,  198,    0,  199,  557, 1797, 2122,   19,  267, 1189,
        1196,  789,  466, 1320,  207,   28, 2122,    3,  437,  335,  263,   50,
         325,  152,  198,    0,   37,  267,   15,  902,  113,  789,  466,   64,
         488,    4,   66,  158,  267,  105,  528, 1797, 2122,    1,  152,  198,
           5,  410])

In [141]:
my_embedding = Embeddings(512, len(vocab_list))
idx = np.load(data_list[0])[:10].astype(int)
idx = torch.tensor(idx, dtype=torch.int64, device=device)
my_embedding(idx)

tensor([[-65.7696,   4.6158,  -7.5767,  ...,  26.4757,  14.1369,  21.1667],
        [ 31.3081,  -4.5238, -30.5610,  ..., -21.5612,   3.6226, -21.3581],
        [  2.7889,   8.0909, -22.0422,  ...,  13.9054,  16.0605,  -1.5210],
        ...,
        [-44.6038,   5.2266, -31.4721,  ..., -20.8467,  37.2234, -13.7966],
        [-21.8527,  34.9529,  -0.3339,  ..., -13.8139,  14.5244,  20.4514],
        [ -9.8245, -54.6033,   3.9819,  ...,  33.5087,  37.8419,  36.8506]],
       grad_fn=<MulBackward0>)

In [142]:
idx

tensor([  50,  325,  152,  198,    0,  199,  557, 1797, 2122,   19])

In [143]:
my_embedding(idx).shape

torch.Size([10, 512])

In [55]:
def clones(module, N):
    "Produce N identical layers."
    return nn.ModuleList([copy.deepcopy(module) for _ in range(N)])

In [56]:
class MultiHeadedAttention(nn.Module):
    def __init__(self, h, d_model, dropout=0.1):
        "Take in model size and number of heads."
        super(MultiHeadedAttention, self).__init__()
        assert d_model % h == 0
        # We assume d_v always equals d_k
        self.d_k = d_model // h
        self.h = h
        self.linears = clones(nn.Linear(d_model, d_model), 4)
        self.attn = None
        self.dropout = nn.Dropout(p=dropout)

    def forward(self, query, key, value, mask=None):
        "Implements Figure 2"
        if mask is not None:
            # Same mask applied to all h heads.
            mask = mask.unsqueeze(1)
        nbatches = query.size(0)

        # 1) Do all the linear projections in batch from d_model => h x d_k
        query, key, value = \
            [l(x).view(nbatches, -1, self.h, self.d_k).transpose(1, 2)
             for l, x in zip(self.linears, (query, key, value))]

        # 2) Apply attention on all the projected vectors in batch.
        x, self.attn = attention(query, key, value, mask=mask,
                                 dropout=self.dropout)

        # 3) "Concat" using a view and apply a final linear.
        x = x.transpose(1, 2).contiguous() \
            .view(nbatches, -1, self.h * self.d_k)
        x = torch.squeeze(x)
        return self.linears[-1](x)

def attention(query, key, value, mask=None, dropout=None):
    "Compute 'Scaled Dot Product Attention'"
    d_k = query.size(-1)
    scores = torch.matmul(query, key.transpose(-2, -1)) \
             / math.sqrt(d_k)
    if mask is not None:
        scores = scores.masked_fill(mask == 0, -1e9)
    p_attn = F.softmax(scores, dim = -1)
    if dropout is not None:
        p_attn = dropout(p_attn)
    return torch.matmul(p_attn, value), p_attn


In [57]:
class PositionwiseFeedForward(nn.Module):
    "Implements FFN equation."
    def __init__(self, d_model, d_ff, dropout=0.1):
        super(PositionwiseFeedForward, self).__init__()
        self.w_1 = nn.Linear(d_model, d_ff)
        self.w_2 = nn.Linear(d_ff, d_model)
        self.dropout = nn.Dropout(dropout)

    def forward(self, x):
        return self.w_2(self.dropout(F.relu(self.w_1(x))))


In [58]:
class PositionalEncoding(nn.Module):
    "Implement the PE function."

    def __init__(self, d_model, dropout, max_len=5000):
        super(PositionalEncoding, self).__init__()
        self.dropout = nn.Dropout(p=dropout)

        # Compute the positional encodings once in log space.
        pe = torch.zeros(max_len, d_model)
        position = torch.arange(0., max_len).unsqueeze(1)
        div_term = torch.exp(torch.arange(0., d_model, 2) *
                             -(math.log(10000.0) / d_model))
        pe[:, 0::2] = torch.sin(position * div_term)
        pe[:, 1::2] = torch.cos(position * div_term)
        pe = pe.unsqueeze(0)
        self.register_buffer('pe', pe)

    def forward(self, x):
        x = x + Variable(self.pe[:, :x.size(1)],
                         requires_grad=False)
        return self.dropout(x)

In [59]:
class Encoder(nn.Module):
    "Core encoder is a stack of N layers"

    def __init__(self, layer, N):
        super(Encoder, self).__init__()
        self.layers = clones(layer, N)
        self.norm = LayerNorm(layer.size)

    def forward(self, x, mask):
        "Pass the input (and mask) through each layer in turn."
        for layer in self.layers:
            x = layer(x, mask)
        return self.norm(x)

class LayerNorm(nn.Module):
    "Construct a layernorm module (See citation for details)."
    def __init__(self, features, eps=1e-6):
        super(LayerNorm, self).__init__()
        self.a_2 = nn.Parameter(torch.ones(features))
        self.b_2 = nn.Parameter(torch.zeros(features))
        self.eps = eps

    def forward(self, x):
        # mean = torch.Tensor(x.mean(-1, keepdims=True)).to('cuda')
        # std = torch.Tensor(x.std(-1, keepdims=True)).to('cuda')
        # x = torch.Tensor(x).to('cuda')
        mean = x.mean(-1,keepdim=True)
        std = x.std(-1,keepdim=True)
        return self.a_2 * (x - mean) / (std + self.eps) + self.b_2

class SublayerConnection(nn.Module):
    """
    A residual connection followed by a layer norm.
    Note for code simplicity we apply the norm first as opposed to last.
    """
    def __init__(self, size, dropout):
        super(SublayerConnection, self).__init__()
        self.norm = LayerNorm(size)
        self.dropout = nn.Dropout(dropout)

    def forward(self, x, sublayer):
        "Apply residual connection to any sublayer function that maintains the same size."
        return x + self.dropout(sublayer(self.norm(x)))

class EncoderLayer(nn.Module):
    "Encoder is made up of two sublayers, self-attn and feed forward (defined below)"
    def __init__(self, size, self_attn, feed_forward, dropout):
        super(EncoderLayer, self).__init__()
        self.self_attn = self_attn
        self.feed_forward = feed_forward
        self.sublayer = clones(SublayerConnection(size, dropout), 2)
        self.size = size

    def forward(self, x, mask):
        "Follow Figure 1 (left) for connections."
        x = self.sublayer[0](x, lambda x: self.self_attn(x, x, x, mask))
        return self.sublayer[1](x, self.feed_forward)

In [60]:
class TransformerEncoder(nn.Module):
    """
    A standard Encoder-Decoder architecture. Base model for this and many
    other models.
    """

    def __init__(self, encoder, src_embed, batch_size, d_model, n_class):
        super(TransformerEncoder, self).__init__()
        self.encoder = encoder
        self.src_embed = src_embed
        self.linear = nn.Linear(d_model, n_class)

    def forward(self, src, src_mask):
        "Take in and process masked src and target sequences."
        enc = self.encoder(src, src_mask)
        # flat = enc.reshape(-1).unsqueeze(0)
        lin = self.linear(enc)
        result = F.softmax(lin, dim=1)
        return result

    def encode(self, src, src_mask):
        return self.encoder(self.src_embed(src), src_mask)

In [61]:
N=6
d_model=128
d_ff=2048
h=8
dropout=0.1
batch_size=10
n_class=10
src_vocab = len(vocab_list)

In [62]:
c = copy.deepcopy
attn = MultiHeadedAttention(h, d_model)
ff = PositionwiseFeedForward(d_model, d_ff, dropout)
position = PositionalEncoding(d_model, dropout)
model = TransformerEncoder(
    Encoder(EncoderLayer(d_model, c(attn), c(ff), dropout), N),
    nn.Sequential(Embeddings(d_model, src_vocab), c(position)),
    batch_size,
    d_model,
    n_class
)

In [158]:
device = torch.device('cuda' if torch.cuda.is_available() else 'gpu')
model = model.to(device)

In [159]:
def _select_examples(X, maxlen):
    begin = np.random.randint(len(X) - maxlen)
    return X[begin: begin + maxlen]


def next_batch(X, batch_size, maxlen):
    x = np.zeros(shape=[batch_size, maxlen + 1])
    choices = np.random.randint(len(X), size=batch_size)
    for idx, choice in enumerate(choices):
        x[idx, :-1] = _select_examples(X[choice], maxlen)
        x[idx, -1] = choice
    Y = np.expand_dims(x[:, -1], 1).copy()
    x = x[:, :-1].copy()
    return x, Y

In [160]:
x, y = next_batch(result, batch_size, d_model)

In [161]:
x[1].astype(int)

array([  11, 1338,   66, 1069, 2009,  111,  147,    1,   44,   76,   13,
         75,  212,   28,  765,  200, 1061,  451,   20,    1,  316,    5,
         24,  303, 1658,   11, 1338,    2,   44,   25,   42,  309,  862,
        291, 1948,  227,   11,   76,    1,  474,  239, 3128,    1, 3128,
         12,   34,   36,  824,  640, 6707,    0,  317,  663, 1534,    5,
        575,    6,  765,  200,    3,    8,  231,  547,    1,   14,    0,
        395,  160,  150, 6851, 5658,  640, 6707,    4,  239,  129,  824,
          3,  316,   30,    7,  191,   95, 1136,    1,   96,  794,  640,
         20,    6,  570,  522,  207,  308,  291,    4,    3,  795,  104,
         13,  269,   11,  547,    0,  230,  249,    1,   14,    0,   25,
         13,   98,   49,   27,  137,   18, 3071,  824,  640,   50, 1271,
       4623,    4,   11,  295,   63,  231,   96])

In [162]:
x = torch.tensor(x, dtype=torch.float, device=device)
y = torch.tensor(y, dtype=torch.long, device=device)
y = torch.squeeze(y)

In [163]:
def get_criterion(model, lr=0.005):
    criterion = nn.CrossEntropyLoss()
    optimizer = torch.optim.Adam(model.parameters(),lr)
    return criterion, optimizer

In [164]:
criterion, optimizer = get_criterion(model)

In [ ]:
num_iterations = 100000
dim_model = 128
batch_size= 10240

X = result
for iter in range(num_iterations):
    x, y = next_batch(X, batch_size, dim_model)
    x = torch.tensor(x, dtype=torch.float, device=device)
    y = torch.tensor(y, dtype=torch.long, device=device)
    y = torch.squeeze(y)
    criterion, optimizer = get_criterion(model)
    optimizer.zero_grad()
    output = model(x, None)
    loss = criterion(output,y)
    if iter % 100 == 0:
        _, preds = torch.max(output, dim=1)
        print("Iteration {}: loss= {}, accuracy= {}".format(
            iter,loss.item(), float(torch.sum(preds==y).item()/batch_size)))
    loss.backward()
    optimizer.step()

Iteration 0: loss= 2.244738817214966, accuracy= 0.19423828125
Iteration 100: loss= 2.238743543624878, accuracy= 0.2013671875
Iteration 200: loss= 2.2390854358673096, accuracy= 0.20419921875
Iteration 300: loss= 2.2391865253448486, accuracy= 0.19443359375
Iteration 400: loss= 2.2368602752685547, accuracy= 0.204296875
Iteration 500: loss= 2.2372307777404785, accuracy= 0.20146484375
Iteration 600: loss= 2.2422876358032227, accuracy= 0.19716796875
Iteration 700: loss= 2.234327793121338, accuracy= 0.2052734375
Iteration 800: loss= 2.238388776779175, accuracy= 0.198828125
Iteration 900: loss= 2.243783712387085, accuracy= 0.19765625
Iteration 1000: loss= 2.236576557159424, accuracy= 0.20400390625
Iteration 1100: loss= 2.238525867462158, accuracy= 0.20322265625
Iteration 1200: loss= 2.2429122924804688, accuracy= 0.197265625
Iteration 1300: loss= 2.234954833984375, accuracy= 0.2056640625
Iteration 1400: loss= 2.2398884296417236, accuracy= 0.196875
Iteration 1500: loss= 2.2472012042999268, accur

Iteration 12700: loss= 2.239049196243286, accuracy= 0.1986328125
Iteration 12800: loss= 2.249934673309326, accuracy= 0.1853515625
Iteration 12900: loss= 2.2445991039276123, accuracy= 0.1962890625
Iteration 13000: loss= 2.242706298828125, accuracy= 0.19443359375
Iteration 13100: loss= 2.2399590015411377, accuracy= 0.199609375
Iteration 13200: loss= 2.2438242435455322, accuracy= 0.1951171875
Iteration 13300: loss= 2.245129108428955, accuracy= 0.192578125
Iteration 13400: loss= 2.2398483753204346, accuracy= 0.19697265625
Iteration 13500: loss= 2.246515989303589, accuracy= 0.19130859375
Iteration 13600: loss= 2.24682354927063, accuracy= 0.1900390625
Iteration 13700: loss= 2.2456953525543213, accuracy= 0.1884765625
Iteration 13800: loss= 2.244171619415283, accuracy= 0.19208984375
Iteration 13900: loss= 2.243431568145752, accuracy= 0.19306640625
Iteration 14000: loss= 2.2432923316955566, accuracy= 0.195703125
Iteration 14100: loss= 2.235433578491211, accuracy= 0.20615234375
Iteration 14200: 